### ISSUE TITLE
Excel_Toolkit: Trigger recalculate workbook on first BHoM method call in a session

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#108]
At the moment it's easy to forget to press 'ctrl+alt+F9' to make sure all the BHoM methods recalculate and work, and it's also difficult for new users. The initial reaction is that something is broken. 

Suggest we keep the ctrl+alt+F9 to recalculate, but add a trigger to recalculate the workbook as being when any BHoM method is called for the first time in a session. 

Thoughts appreciated @IsakNaslundBh , @awakeman

**Comment by IsakNaslundBh** [comment]
the ctrl+alt+f9 recalculate is not ours, but built-in in excel, so will have that whatever we do :)

Maybe doing a full recalculate could be a bit brutal if someone has set up some non-BHoM related stuff they do not want re-calculated or similar. But maybe re-running all BHoM-methods on startup/first new method call could be worth considering!

**Comment by rwemay** [comment]
Thanks @IsakNaslundBh  - it does need a balance. In my experience, once a sheet/book has gotten so large that updating calculations takes time, the user turns off auto-calculate (basically an opt-in for not updating a sheet). As I understand it, out of the box, Excel will rerun calculations before it _closes_ rather than opens unless you turn defaults off. 

The idea/compromise we thought of was basically if you change a cell with a BHoM object/method in it, it will force re-calculate anything in the book with BHoM methods in. 

I'm still not completely clear what we've done that's different to the way Excel/formulae operate (i.e. why do we need to manually hit ctrl+alt+f9). Is it because there are dependencies hidden from Excel such that it doesn't know to recalculate some cells automatically?

**Comment by IsakNaslundBh** [comment]
Main reason, unless things have changed a lot since @awakeman took over the toolkit, is that you can not simply store the full meaning of a BHoMObject in an excel-cell. Instead a reference, GUID, is stored.

As, if you do a sum and get 5.6 as value in the cell, then there is no need to recalculate the 5.6 before you use it, as the actual value and the text displayed are the same.

For the BHoM when you create say a Point the actual value will be stored in a background project,and the cell will display something like `Point [ju7bOm+q]`. Ofc, the actual text in the cell is not enough to be used OOTB, but you need the background project for it to work. This is why you need to re-calculate, to make sure that the project is loaded up with references to all the objects used throughout the script.
I know @awakeman has done some work for serialising all of the used objects out to a hidden sheet, but think there were some performance tradeoffs discussed with this, but think Andrew will know better exactly were we ended up with that.

Hope this makes sense?

**Comment by awakeman** [comment]
>I'm still not completely clear what we've done that's different to the way Excel/formulae operate (i.e. why do we need to manually hit ctrl+alt+f9). Is it because there are dependencies hidden from Excel such that it doesn't know to recalculate some cells automatically?

In regular excel it is only dealing with primitive types (numbers and strings) which are stored in the cell, when you open a workbook nothing is calculated but if you change the value in a cell any cells that depend on that one recalculate their formula. The BHoM objects we return exist instead in memory and a handle to them (in string form) is stored in the cell. Absent a forced recalculation, on a new session the handle cannot be resolved to anything so any cell dependent on an unresolvable BHoM object handle will fail to run when it updates in normal operation.

We did, for a short while, have all the BHoM objects in a sheet serialised into a hidden sheet upon save but this required a scan of all of the used cells in a workbook for BHoM object handles in use (to prevent serialising everything that ever existed) which was very slow for large workbooks for obvious reasons.

The best way to do it for the optimum user experience would be to track all changes and effectively write our own reference counting and garbage collection and _then_ serialise the objects in the internal dictionary. Tracking those changes requires hooking into a lot of events like moving cells and inserting rows/columns that adds a lot of complexity and would be pretty susceptible to errors resulting in unresolvable handles and memory leaks (that turn into storage leaks).

As we discussed in person on Friday the simplest way to do this, in my opinion, without touching peoples non-BHoM sheets would be just to write a flag the first time a BHoM method is used and recalculate the workbook on load if this flag is present.
