### ISSUE TITLE
Excel_Toolkit: Exposing BHoM Datasets

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#139]
#### Description:

Linked to #130 we need to be able to load datasets in Excel. Ideally this would be done in a way that it sets the 'Data Validation' - providing a dropdown list of dataset entry names. Test on the UK Steel Section properties or Materials as an example implementation. There will need to be some hidden XML or other place to store the dataset/validation object reference. 

@IsakNaslundBh , @al-fisher , @kayleighhoude keen to get you in on this/testing/commenting as will be a big unlocker.

**Comment by IsakNaslundBh** [comment]
@rwemay I actually think it is already working. It is far too hidden now without the rightclick menu, but you can still access the datasets in excel via ctrl+shit+b.

![Materials Excel](https://user-images.githubusercontent.com/22005920/62688544-5e1c7880-b9c9-11e9-9603-33e789f050f2.gif)

might be worth re-adding just these guys in the right click menu? Alt, make a small little toolbar button or something if the right click menu turns out to slow.

**Comment by rwemay** [comment]
Got it thanks! Yes.... need to sort out the right click menu, but also the icons - match GH/DYN. 

Closing this now, beautiful.
