### ISSUE TITLE
Update the CreateObject component to support the new creator from type

### ISSUE THREAD

**Issue by adecler** [BHoM/Excel_UI#161]
In sort, Excel now needs to support the new functionality provided in https://github.com/BHoM/BHoM_UI/pull/147

It kind of works if you provide all the properties but that not the general suer case (e.g. the Guid is never an input). Here's what I have in mind but happy for any other approach to support this:
```
=Create.Geometry.SettingOut.Level?by_Properties(5,,"test",,,)
```

@al-fisher  FYI

**Comment by awakeman** [comment]
How does this differ from `CreateCustom` with a type?

**Comment by al-fisher** [comment]
> How does this differ from CreateCustom with a type?

It will replace it. Wider discussion here: https://github.com/BHoM/BHoM_UI/issues/124

Although in short: The CreateObject component has been upgraded to enable access to object initialiser style syntax effectively - along side any additional create methods. Putting all methods of creating a Type in one place/component.

CreateCustom (in future PR) will therefore focus on simply creating a object of CustomObject type.

Hope makes sense?

**Comment by awakeman** [comment]
Thanks, yeah that makes sense. The reason I ask is because the way we solved `CreateCustom` was to make it function like `CreateDictionary` in taking a list of keys and a list of values. The obvious problem there is there is a fundamental discoverability problem (you need to first know what properties the object *has* to use it effectively).

As @adecler points out we can do it with optional positional parameters but that can become long-winded.

**Comment by adecler** [comment]
The key thing to keep in mind is that we are aiming to eliminate most of the Engine.Create methods (as they too often just trivial mapping of parameters to properties). So it is important to make sure the user is allowed to fill in only the necessary properties to avoid a degraded experience from what we currently have. 

Agreed that the list of keys and values is not a good solution here for the reason you mentioned. This is why I feel tapping on the intellisense is a better way forward as it is quite quick to skip the properties you don't care about without getting lost in the count. I wonder though if there is a way to simplify the method once it has been completed the first time and if it would improve the user experience or actually make it worst.

The suggestion I made is just that though and is nothing more than the first solution that I could think of. So this issue is more about the exploration of the possible solutions than their implementation.

**Comment by awakeman** [comment]
Bumping to next milestone since this needs some thought.

**Comment by al-fisher** [comment]
This needs to be prioritised as until this feature is implemented we are still reliant on Create methods as the only mechanism for creating objects from only defining properties.
This means we can not start the process of removing redundant Create methods across the engines. 
@awakeman 

As an aside and FYI @adecler - Good to capture in conversations around versioning tomorrow etc. what the approach will be for deprecating (or simply removing and having handled by Versioning_Toolkit) for this case of removal of redundant Create methods.

**Comment by awakeman** [comment]
Small point-of order that has only just come to mind, These are actually already supported on account of being supported in BHoM_UI.

The *only* thing that needs to be under discussion is overwriting their name generation because at present they have the type list like with the rest of the create methods. 

e.g. 
![image](https://user-images.githubusercontent.com/18450341/70246854-4636e480-1770-11ea-8285-25aea46e5b13.png)
becomes:
![image](https://user-images.githubusercontent.com/18450341/70246897-5bac0e80-1770-11ea-91d8-99cd8c21f437.png)
