### ISSUE TITLE
BHoM.Explode function to explode lists and dictionarys

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#181]
#### Description:

I think this might work on dictionaries already, but doesn't for lists. Excel being different to GH/Dynamo, it's difficult to see what's inside a list, so it would be useful to be able to explode the list using the same explode function.

**Comment by awakeman** [comment]
Lists of BHoM objects *should* work, shout if it doesn't, by exploding all objects within the list but indeed it'd be good to be able to properly explode lists of primitives and strings into a simple 1x*n* array.

**Comment by rwemay** [comment]
I couldn't get it to work, but would also suggest we explode any list. Suggest you do a quick test script and use as a basis for testing any list.

**Comment by adecler** [comment]
It kind of work and kind of doesn't.

It does explode the items in a list if they are BHoM objects (tried to explode a list of types and it failed). The issue is that it doesn't just explode the list, it explode the items in that list too. So it's kind of a all or nothing situation:

![image](https://user-images.githubusercontent.com/16853390/89864868-4a5cb100-dbdf-11ea-9b77-ce67ca93a5f7.png)


Unless we add an extra parameter to this method, it is difficult to know what the user wants. An alternative is to start exploiting the currently empty UI section of the ribbon to have components specifically tailored to Excel needs. In this case, we could start with an 'ExtendList' or something. 

Just some quick thoughts until I get into that part next sprint.

**Comment by adecler** [comment]
Now solved by the `Expand list` button in the ribbon
