### ISSUE TITLE
Excel Issue: Pushing combinations direction to software

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Excel_UI#21]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by awakeman** [comment]
This issue was regarding a double Push when using the Push Function. With some software that caused issues with the second push superseding the first.

@jdarcyBHE I believe this was prior to the changes brought in by #20 (Migration to BHoM_UI). Is that the case? Would be good if you could test this and let me know so we can close it if it is no longer an issue.
