### ISSUE TITLE
Excel_Toolkit: Dataset Issue

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#252]
#### Description:
Upon placing a dataset, certain parts of the dataset break into multiple entries:
![image](https://user-images.githubusercontent.com/34316256/93379806-5c5bf000-f82c-11ea-8f3f-dc50fccc8c60.png)
Expected result:
![image](https://user-images.githubusercontent.com/34316256/93379915-86151700-f82c-11ea-861c-72a9718f8e09.png)

This is not isolated to a single dataset:
![image](https://user-images.githubusercontent.com/34316256/93379809-5f56e080-f82c-11ea-9e72-aa7960b863c4.png)

#### Expected behaviour:
These should be a single entry.

**Comment by adecler** [comment]
I think you are not on the latest installer. The way the content is divided where you had commas is caused by an old way of creating the drop-down.

This is what I have from today's installer:

![image](https://user-images.githubusercontent.com/16853390/93418053-1494a180-f8dc-11ea-83f7-c4924c792d9b.png)

Feel free to reopen if I am wrong but I am pretty confident on that one 😄
