### ISSUE TITLE
Additional parameters in method name

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Excel_UI#256]
#### Description:

The formula for some of the adapter methods, namely the Push and the Execute has slightly strange formula in excel.

`Adapter.Push?by_BHoMAdapter_IEnumerableOfObject_String_PushType_ActionConfig_Boolean_Boolean_Boolean`

and

`Adapter.Execute?by_BHoMAdapter_IExecuteCommand_ActionConfig_Boolean_Boolean_Boolean`

The strange part is the extra 2 `_Boolean` at the end. Think it should be:

`Adapter.Push?by_BHoMAdapter_IEnumerableOfObject_String_PushType_ActionConfig_Boolean`

One commonality between the two methods is that they both return an `Output<T1,T2>`, something that the other adapter methods do not do.

This has also changed since prior to the refactoring. Even if you might expect to have to update some things to get it running post the refactoring, good if as much as possible could stay the same.

#### Steps to reproduce:

Add a push method to a sheet

**Comment by adecler** [comment]
That is by design. See this PR: https://github.com/BHoM/Excel_Toolkit/pull/251
 Obviously some backward compatibility would be nice 😋 . I'll see what I can do about that.

**Edit:** thinking back about this, the formula name is based on the `Caller.InputParams` so it is weird that it would be affected by the functionality on that PR. I'll get that fixed.
