### ISSUE TITLE
Allow functions to loop for each input

### ISSUE THREAD

**Issue by tiagogrossi** [BHoM/Excel_UI#278]
#### Description:
Currently Excel doesn't seems to allow a function to iterate multiple times based on the number of inputs, it would be great to have it enabled somehow. One good example of the equivalent in Grasshopper (collectionName input): 
![image](https://user-images.githubusercontent.com/20777038/104910698-9aefeb80-5981-11eb-8c4c-c763b2aac9a5.png)

In Excel I'm trying simply this (a bit messy but hopefully the adapter formula clarifies, with multiple entries in the collectionName input):
![image](https://user-images.githubusercontent.com/20777038/104911141-4c8f1c80-5982-11eb-8fd2-73bc61c1bba2.png)

**Comment by tiagogrossi** [comment]
@adecler I'm not sure if you're able to help out with this one? Maybe it is already possible to do it and I just don't know. Any advice?  
@BSochacki and @enarhi FYI

**Comment by adecler** [comment]
Both Dynamo and Grasshopper provide lacing, Excel doesn't. 
Different environment, different way of working. Each UI serves a different purpose and they are not meant to perfectly replace each other. 
Following general workflow in Excel, if you need to run an operation multiple times, duplicate it in multiple cells. The task is much easier than in GH since Excel automatically update target cells during copy-paste so there is no rewiring needed.
