### ISSUE TITLE
Compute of List Not Functioning

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#311]
#### Description:
Use of LCA Evaluate Method for single object functional, when adding a list of elements (either by drag selection or a condensed list in a cell), method errors out:

![image](https://user-images.githubusercontent.com/34316256/130644417-038bfd98-8443-48d5-b8f0-6290edd941f3.png)

Method is functional in Grasshopper with multiple elements:
![image](https://user-images.githubusercontent.com/34316256/130644600-d0c4e873-ceff-4f83-8790-7a3755c5dad0.png)

**Comment by kayleighhoude** [comment]
@michaelhoehn for your reference

**Comment by adecler** [comment]
@kayleighhoude , can you provide a file for debugging please ?

**Comment by kayleighhoude** [comment]
@adecler test file located here: https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FExcel%5FToolkit%2FIssue%20311

**Comment by adecler** [comment]
I am not sure I understand where the problem is. Are you complaining that Excel doesn't support lacing like Grasshopper does ?

The `EvaluateEnvironmentalProductDeclaration` method takes a single `IElementM` as first input, not a list. Althouh potentially a bit cryptic, this is what the error message is trying to tell you:

![image](https://user-images.githubusercontent.com/16853390/131437242-0919ef6e-0f50-475f-b5b1-18510e78d2a0.png)

So technically, you should have one result cell per row.

**Comment by michaelhoehn** [comment]
@kayleighhoude typically I call `EvaluateEnvironmentalProductDeclaration()` once per cell in cases like this and use `TotalMetricQuantity()` with a =sum() as the result.
