### ISSUE TITLE
Internalise in Excel Bug

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#315]
#### Description:
Upon attempting to internalise a list of objects that had been expanded, the objects below the first disappeared:
![image](https://user-images.githubusercontent.com/34316256/133793345-7e81b031-3619-454f-9785-0bf83cfd6141.png)

@michaelhoehn heads up

**Comment by michaelhoehn** [comment]
@kayleighhoude I've noticed this behaviour in Grasshopper a long time ago and found it was related to my BHoM build at the time. I'm not entirely sure of the error that caused it, but since then I've not run into this issue again. Can you verify the installer that you're using and that you're also not on any custom code that has been compiled to help understand the error a bit more?

**Comment by kayleighhoude** [comment]
thanks for the suggestion @michaelhoehn i've just installed today's alpha and the same error is occurring: 
![image](https://user-images.githubusercontent.com/34316256/134186834-0a67f167-29e6-40d4-8fa3-34da7d3353b9.png)
