### ISSUE TITLE
Excel_Toolkit: Having BHoM installed appears to cause Excel to crash randomly

### ISSUE THREAD

**Issue by rboulton-BH** [BHoM/Excel_UI#334]
#### Description:

When using Excel generally with BHoM installed (although not necessarily actively using BHoM methods) I have noticed that Excel frequently freezes and has to be forced to shut down. When I uninstall BHoM the issue seems to go away.

#### Steps to reproduce:

I haven't really noticed a pattern in specific things that I did that caused the crash so can't easily reproduce the problem. Maybe there was a correlation with entering info or formulae into a cell but that's a pretty common action in Excel so unfortunately isn't very specific

#### Expected behaviour:

Excel freezes and you get the spinning blue wheel of death. Only way out I've found is to end it in Task Manager

**Comment by alexissantella** [comment]
Description:
When using excel using BHoM methods using Beta 5.0 excel freezes and has to be forced to shut down. When trying to reopen, it will never load fully and open.

Steps to reproduce:
The same issue occured several times with several versions of the test file below.

Expected behaviour:
Excel file either wont open, or it freezes and needs to be closed. 

Test file(s):
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&OR=Teams%2DHL&CT=1644939401689&sourceId=&params=%7B%22AppName%22%3A%22Teams%2DDesktop%22%2C%22AppVersion%22%3A%2227%2F22010300409%22%7D&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FExcel%5FToolkit%2FIssue%20334&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b

**Comment by alexissantella** [comment]
BHoM installer thinks the files are still open that crashed. 

![image](https://user-images.githubusercontent.com/69594663/154106221-c129bf57-42d7-4bf1-af36-b41acc1cc3cc.png)

**Comment by adecler** [comment]
After using Excel intensively those last few days, I also noticed crashes. For me, they seems to generally occur when I edit a formula. 
Looking at the Event Viewer, the same error is registered ever time :

```
Faulting application name: EXCEL.EXE, version: 16.0.14326.20784, time stamp: 0x62000e68
Faulting module name: RICHED20.DLL, version: 16.0.14326.20504, time stamp: 0x615f6350
Exception code: 0xc0000005
Fault offset: 0x000000000000e0b6
Faulting process ID: 0x58d8
Faulting application start time: 0x01d8216cf89ecddc
Faulting application path: C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE
Faulting module path: C:\Program Files\Microsoft Office\root\vfs\ProgramFilesCommonX64\Microsoft Shared\OFFICE16\RICHED20.DLL
Report ID: 9fd72601-5d15-4ec7-9697-65ec0685639a
Faulting package full name: 
Faulting package-relative application ID: 
```

A quick search on this lead me to this issue on Excel-DNA that might be a good place to start: https://github.com/Excel-DNA/IntelliSense/issues/87

**Comment by adecler** [comment]
@alexissantella, could you check your event viewer too to see if the error you get is the same as mine. Here's how to do that:

1. Search for "event viewer" in your windows start menu:

![image](https://user-images.githubusercontent.com/16853390/154179847-40015fce-3137-4331-9aec-0cfa859cc424.png)

2. In the top left menu, go to `Windows Logs` > `Application`:

![image](https://user-images.githubusercontent.com/16853390/154180104-3c160fce-539c-4f0a-90b1-a1e88ea39ba8.png)

3. Click the 'Filter current log" button on the left side of the app:
![image](https://user-images.githubusercontent.com/16853390/154180307-22fc176d-d26a-46fc-a7d7-a31cb45eedf4.png)

4. In that pop-up dialog, select `Critical` and `Error` for the event level:

![image](https://user-images.githubusercontent.com/16853390/154180434-1dff45e8-4de6-4857-80b3-5a8487672ac5.png)

5. Browsing through the recent events, you should find some that mention Excel:

![image](https://user-images.githubusercontent.com/16853390/154180643-11a8e75f-524d-4376-9f39-c66daaed1e8e.png)

**Comment by adecler** [comment]
After a chat with @FraserGreenroyd , we agreed the best is to first update our reference to Excel_DNA to the latest version as it seems to be a bug on their side. We will do this at the beginner of next milestone to have as much time as possible to detect other potential issues the upgrade might have caused.

**Comment by travispotterBH** [comment]
Adding some information to support other's experience:

@adecler I am receiving the same error: 
![image](https://user-images.githubusercontent.com/96432552/164320930-e282fe6f-b460-4cc9-a0d7-9b2480dcbf47.png)
and often it is paired with this error: 
![image](https://user-images.githubusercontent.com/96432552/164320869-ae9fb2b4-6cf9-4af1-98ef-c2dbd37ab7f9.png)

Steps to reproduce:
Only occasionally when filling a formula. I am hesitant to say this, because not sure if it actually is related, but it seems like it occurs more often the first time that I am using a new object or method that has not yet previously been used in the specific excel workbook. As in, it has not yet been registered to the BHoM_CallersHidden worksheet.
