### ISSUE TITLE
BHoM Formulae Disappears Upon Enable Edit

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#337]
#### Description:
![image](https://user-images.githubusercontent.com/34316256/158391995-e7e2664b-3f52-4589-a7ab-b80c58883976.png)

Upon clicking Enable Editing with a downloaded Excel sheet, all of the BHoM formulae disappears/turns to errors:
![image](https://user-images.githubusercontent.com/34316256/158391618-b135ebb8-85fb-4ec1-9dcf-8150fc644133.png)

Upon opening a second time (post clicking enable edit- the cells reappear as they should?!)
![image](https://user-images.githubusercontent.com/34316256/158392066-fabdde78-19da-48a5-946f-03e8b842f14d.png)

@michaelhoehn is this happening for you as well?

#### Test file(s):
See the test files here for download (to reproduce error): https://burohappold.sharepoint.com/sites/Direction/designtechnology/BHoM%20Samples%20Library/Forms/AllItems.aspx?id=%2Fsites%2FDirection%2Fdesigntechnology%2FBHoM%20Samples%20Library%2FMEP%2F00003%5FMEP%20Duct%20and%20Pipe%20Quantities&viewid=c683ab7e%2D748f%2D4708%2D9132%2Da968b4d1e52b

**Comment by alexissantella** [comment]
Having the same issue, when opened every cell has to be replaced, and reworked. Also I had trouble opening it once it  was downloaded. 
![image](https://user-images.githubusercontent.com/69594663/158658691-2b290d87-a303-4690-9067-75cc7f4750f5.png)

**Comment by FraserGreenroyd** [comment]
An email requesting further information to be filled out to support this issue was sent to @kayleighhoude at 10:12AM BST on Monday 4th April 2022 asking for more information to be provided to the issue would have to be closed as unreproducible. More information has not been forthcoming, and I have not been able to reproduce the issue reliably from the information provided. As such, I am closing this issue as unreproducible at this time. If more information becomes available, and the steps requested filled in appropriately at a later date, the issue can be reopened for further investigation.
