### ISSUE TITLE
Excel_Toolkit: Dropdown menu providing values from alternate sheet

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#340]
#### Description:
![image](https://user-images.githubusercontent.com/34316256/160799115-f6ea960b-d953-4fd1-a25f-f013ccd559ad.png)

The value is appearing to have calculated correctly, but the dropdown menu from a previous sheet is appearing - did receive a pop up stating that the format for the cell was incompatible (?) 

Issue appeared during Hackademy presentation :) 

#### Test file(s):
[]
https://burohappold.sharepoint.com/:x:/r/sites/Direction/designtechnology/Events%20Log/220328_Hackademy%205.0/Datasets%20and%20Calculations/How%20to%20Use%20a%20Dataset%20in%20Excel.xlsx?d=w7f55126c242640a68a32394a47fbd961&csf=1&web=1&e=UVgtCc

**Comment by kayleighhoude** [comment]
![ConcreteDatasetIssueGit](https://user-images.githubusercontent.com/34316256/160801367-32ddf1b8-6a85-45cc-8b03-b5fa85593e8f.gif)

**Comment by adecler** [comment]
@kayleighhoude , please make sure to add @FraserGreenroyd to the list of assignees as he is now the one responsible for the UI framework. I help when I have some spare time but I cannot guarantee when this will be the case.

**Comment by FraserGreenroyd** [comment]
An email requesting further information to be filled out to support this issue was sent to @kayleighhoude at 10:12AM BST on Monday 4th April 2022 asking for more information to be provided to the issue would have to be closed as unreproducible. More information has not been forthcoming, and I have not been able to reproduce the issue reliably from the information provided. As such, I am closing this issue as unreproducible at this time. If more information becomes available, and the steps requested filled in appropriately at a later date, the issue can be reopened for further investigation.
