### ISSUE TITLE
Enums Not Updating

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#363]
#### Description:
When new items are added to enums, existing workbooks do not update the enum, where new workbooks show the entirety of the entries in the enum.

![EnumNotUpdating](https://user-images.githubusercontent.com/34316256/192883275-0d05e577-8f9c-40c1-b927-5598f7fcdf9a.gif)

@travispotterBH @michaelhoehn not sure if you have seen this issue as well

**Comment by FraserGreenroyd** [comment]
@kayleighhoude can you provide an existing workbook that is experiencing the issue and an example enum that can be used to attempt to reproduce the issue?

**Comment by travispotterBH** [comment]
I've tried this in an existing workbook of my own and did not have the same unexpected behavior. @kayleighhoude I'd like to see if I can replicate on your file..

**Comment by FraserGreenroyd** [comment]
Investigated with @travispotterBH just now on a call. I can confirm that changing an enum and opening an existing sheet does not load in new enum options.

This is due to the enum options being saved/serialised with the file, but not being updated if the enum has changed. @travispotterBH and I are looking into this now
