### ISSUE TITLE
Excel Object Volumes from Revit

### ISSUE THREAD

**Issue by m-greig** [BHoM/Excel_UI#373]
Hi,

When we're pulling through object properties for structural elements from Revit, the volume values do not match what is shown within Revit. 

E.g. for the structural columns, for the 300x300 SQ RC columns, Revit calculates a volume of 0.243m3 which is 0.3x0.3x2.7 (the height of the column without the slab thickness). 

Within the Revit > BHoM link with excel, the same column shows as 0.27m3 which is 0.3x0.3x3.0 (the full floor to floor height). I assume this is to do with how BHoM is calculating the values but this is giving inconsistency which I cannot seem to resolve. 

I'm using the query function under physical > solid volume > Iframing element

Is there another way to access the volume of structural elements so that they match through with Revit?

![image](https://user-images.githubusercontent.com/58465055/207912303-d4e107bb-ca2b-4196-ad19-4c97382038a8.png)
![image](https://user-images.githubusercontent.com/58465055/207912384-fe9360d9-046d-4fd7-8060-68b52d50769a.png)

**Comment by travispotterBH** [comment]
@IsakNaslundBh @pawelbaran I think this is probably something that stems from how the convert from Revit is set up for columns.  I looked at the code for how the column length is calculated and it seems reasonable being based on a base level and offsets: https://github.com/BHoM/Revit_Toolkit/blob/b39ecfddee8f54caea0cbad7e39d616ffba34022/Revit_Core_Engine/Query/LocationCurve.cs#L109-L134


@m-greig Can you confirm how you've set your offsets and base? 

@IsakNaslundBh I suggest if this does turn out to be a bug, rather than user error, that we move to : https://github.com/BHoM/Revit_Toolkit

**Comment by pawelbaran** [comment]
@travispotterBH you are right about the origin of the problem - Revit calculates volume based on the actual solid that represents the column in 3D, while the converted BHoM framing element spans between tops of floors plus includes the offsets, naturally resulting in different length and volume. I would not consider this a bug, rather a convention that we set out a long time ago together with @IsakNaslundBh and would rather not change it.

However, there is a good news @m-greig - we have 2 other ways of extracting volume/material information that is closer to what Revit shows:
- call `GetRevitParameter` on the element with parameter name equal to _Volume_
- apply [`RevitPullConfig` with `PullMaterialTakeOff` property set to `true`](https://github.com/BHoM/Revit_Toolkit/blob/develop/Revit_oM/Config/RevitPullConfig.cs#L54) as a `PullConfig` input in your `Pull` action - then each pulled element will carry a material takeoff fragment that can be queried using a `MaterialTakeoff` method

**Comment by m-greig** [comment]
Travis and Pawel,

Thanks for your quick response. That's very helpful to know, thank you! I will use the material takeoff property instead for calculating volume.
