### ISSUE TITLE
Excel_Toolkit: Make empty cells cast to valid input

### ISSUE THREAD

**Issue by alexradne** [BHoM/Excel_UI#46]
It is often very useful to have a range (list/array) as input for a method and currently all cells in that range has to be filled in. I think it would be good to have empty cells converted to either zero or null ) depending on the input type.

I suggest if the input takes...

- a single number then an empty cell should be treated as 0
- a single number with default number set, then it should use that number
- a list of numbers, then an empty cell should be treated as 0
- a list of objects, then an empty cell should be treated as null

Maybe we should "trim" the list and remove all the empty cells?
But might not be ideal when the input is required to be multiple equally long lists (like when creating load-combinations as an example).

**Comment by IsakNaslundBh** [comment]
@awakeman is this something you could have a look at fixing? Will help quite a bit in terms of being able to generate nice looking sheets without having to have redundant 0's spread out across things.

maybe something like treating empty cells as `default(T)` for something expecting a `List<T>`  or a single `T` could solve it? I think this will be mostly useful for listinputs, where there are cases where you will want to be able to select a long array, including empty cells implicitly treated as 0-values.

**Comment by awakeman** [comment]
I was thinking about it again this morning after a chat with @johannaisak earlier in the week. The issue is that it is the opposite of another feature, being able to select a sparse range and ignore the blanks (like the range being sent to Push in your loadcases template), á la Grasshopper's Clean Tree.

One thing might be to only do it if `T` is a primitive type (like a number) but not for other values of `T`. Another might be to add a `CleanList`/`CullNullOrEmpty` or something Engine method that you could wrap a range in if a that is what is desired. 

I'm wary of making it behave differently based on what is being passed or expected, especially as there are many cases where a method takes an `Object` for general use but is actually narrowing in on a specific type after that, which would bypass any special treatment certain types were getting.

**Comment by IsakNaslundBh** [comment]
I think what you mentioned there is for the specific case of pushing things though, but might be wrong.

Just from a usage point of view I would like to say empty=0 for methods expecting numbers and empty = "dont care about it" for push. Then I understand what you mean about keeping a sane logic across things, but I would at least expect those two behaviours.

**Comment by IsakNaslundBh** [comment]
Thinking a bit more about this, there might be scope for preforming null-cleanup on the UI/Adapter level for the push. Basically checking for nulls and raising warnings for the ones found then push the rest. If that was done, excel could just go by the `default(T)` approach for empty cells.

Not sure if this is a good idea or not though in general. @adecler @al-fisher @epignatelli

**Comment by awakeman** [comment]
Yeah, that is my thinking too. The UI shouldn't really be responsible for knowing what a Push wants and cleaning accordingly, it should happen at the adapter. That also then leaves a mechanism for the default behaviour to be overridden by a specific adapter if for some reason they want to treat those inputs differently. I've got the `default(T)` change sitting on a branch but I'd think we should address the Pull cleanup first else risk breaking compatibility with people's existing excel workbooks that use sparse ranges.
