### ISSUE TITLE
Excel_Toolkit: Load Cases in FilterQuery coming in as list of characters instead of list of strings

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Excel_UI#47]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by awakeman** [comment]
This is a bug that passing a single cell into a function that wants a `List<object>` or `List<string>` where the referenced cell is a `string` results in a `List<object>` or `List<string>` respectively where the former are `char`s stored as `object`s and the latter contains single character strings. This is because `string` implements `IEnumerable` so is caught by the following block: https://github.com/BHoM/Excel_Toolkit/blob/26ae38cf7a4214ac37c672c666f8997a691d8a46/Excel_UI/UI/Templates/FormulaDataAccessor.cs#L91-L102

In the case the referenced cell is a primitive type the result is a `#NULL!` error as per:

https://github.com/BHoM/Excel_Toolkit/blob/26ae38cf7a4214ac37c672c666f8997a691d8a46/Excel_UI/UI/Templates/FormulaDataAccessor.cs#L103

Desired behaviour is a `List<T>` with a single item: the value in the referenced cell.
