### ISSUE TITLE
Excel_Toolkit: saving spreadsheet takes several minutes

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Excel_UI#55]
Excel is unresponsive for several minutes whenever I save the sheet. Is there something in how the toolkit lets go that causes a delay?

**Comment by awakeman** [comment]
Minutes is concerning, yes all used BHoM objects are serialised and written to a hidden sheet on save so that they remain available when you open the sheet again. There may be a way to do so more efficiently but it will never be zero and will always be proportional to the number of BHoM objects in the workbook (and the number of used cells in the workbook). 

The alternative is that we save nothing and recompute the workbook on load, which may in itself take minutes to do and may also fail if an adapter can't connect to whatever it needs to.

**Comment by rwemay** [comment]
Serialising the BHoM objects in Excel (if not specifically instructed by a user) is a different behaviour to the Grasshopper/Dynamo/Flow based programming UI's. Grasshopper/Dynamo recompute/create the object on load, unless a user has serialised by (for example) 'ToJson' and saving as text/internalised. 

This might be something that Excel has to deviate on due to the fundamental way the UI/format works(?) 

Apologies if I've misunderstood!

**Comment by awakeman** [comment]
Yeah, that's correct. Does, or do we force, the GH canvas update when a file is opened? or does it just recompute when it first needs to (i.e. lazily)?

I'm wary of making it so that opening an excel document automatically executes a network request or some expensive operation. But that is, of course, the same with saving; saving shouldn't result in an overly expensive operation either.

**Comment by rwemay** [comment]
Yes, I believe GH computes whenever a file is opened (unless a component is deactivated). There are issues with GH (and Dynamo) where users have saved active components that a) make requests to external softwares/sockets and or b) have computationally expensive methods. Best practice is to 'deactivate' these before saving and closing. 

Again, all of this is in quite a different UI/environment to Excel, which may necessitate a different approach. Would be good to get @al-fisher and @IsakNaslundBh thoughts.

**Comment by IsakNaslundBh** [comment]
Yes, GH computes the full canvas when you open it, unless you start it with the solver turned off, but then the explicit action is to tell it _not_ to recompute, standard behaviour is to rerun the whole thing. Have some scripts that take their fair time to open for larger projects.
As Rob said, it is best practice to save scripts with adapter connections and similar toggled off, something that could be done in excel as well right now to the best of my knowledge. I.e. something that could be solved by best practice behaviour rather than on the code side. (I forget this from time to time, and even if it is annoying to have to wait for Etabs/Robot/Whatever to open etc, it is not the end of the world, just a min or two of wasted time)

What we have in GH though is the ability to serialise anything, anytime we want (internalise data in GH) so that what ever was used up to that point can be decativated, and only reactivated when needed. 
This would be quite similar to how the "Paste Values" works in excel. No Idea if we are able to hack into that, and make that check for any IObjects and serialise them if it finds any.

![image](https://user-images.githubusercontent.com/22005920/50897643-04d97000-140d-11e9-8603-6ec8b3d89eb6.png)

An alternative approach could be that you select a range of cells and tell them to be serialised. Then only this part of the data would have to be stored in the hidden sheet.

We could then potentially store the location of all cells with BHoM functions and tell excel to recalculate them explicitly when opening the sheet, alternatively leave it to the user to hit crtl+alt+f9.

**Comment by awakeman** [comment]
>What we have in GH though is the ability to serialise anything, anytime we want (internalise data in GH) so that what ever was used up to that point can be decativated, and only reactivated when needed.
This would be quite similar to how the "Paste Values" works in excel. No Idea if we are able to hack into that, and make that check for any IObjects and serialise them if it finds any.

This is one of the things that the current serialisation of everything allows. You can copy a cell, paste values, and be sure it's still going to be there next time you open the application.

Maybe we can hook into an event there, will look into it.

**Comment by JosefTaylor** [comment]
I really like Isak's idea of specifying ranges to be serialized - I think a control panel with a list of ranges would be pretty intuitive. Users could still paste-values excel native data without knowing anything about serialization.
