### ISSUE TITLE
Excel_Toolkit: Result extraction tool

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Excel_UI#73]
A small UI tool for extracting results and exploding them out in a table in excel.

Inputs:
- Adatper - Choose which package to pull from
- Result type 
- Query settings

Then simply hitting go, extracting all the results and exploding out in excel-sheets.

Would be nice to have something like this, working the same for every single adapter.

**Comment by awakeman** [comment]
@al-fisher, @rwemay  and I have discussed something like this before so it's definitely on the horizon to look into at some point. The immediate candidate for this would be finding how we can add BHoM Adapters as an available source for PowerQuery, so that we can lean on that to do most of the heavy lifting (and I think it would allow use from PowerBI to boot).

![image](https://user-images.githubusercontent.com/18450341/53350004-2c7d8c80-3916-11e9-8f43-0e146f85c4ef.png)

**Comment by IsakNaslundBh** [comment]
Ok, cool! Sounds like an interesting approach using the PowerQueries. Nice if we are able to fit it into MS ecosystem!

**Comment by rwemay** [comment]
Following other recent Excel templates, I think there's a way for us to do this without a UI. I will raise an issue in the relevant Repo shortly.
