### ISSUE TITLE
Excel_Toolkit: Create test installer

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#76]

**Comment by rwemay** [comment]
Test script saved here: 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/Excel_Toolkit-Issue76-StructuresTemplate?csf=1&e=vu2bxD

**Comment by alelom** [comment]
## Sample file
Sample file with test data:
https://burohappold-my.sharepoint.com/:x:/p/alessio_lombardi/EUV1mYEShxxNiQ2jaRctWGwBlPfdLdwABU6YPpMt9iBQmA?e=KTgNwK

* General tidy up
* General anonymization
* Insertion of anonymized test data
* Rearrangement of the adapter page. Now there are several adapters ready to export (Robot/Etabs/File Adapter). Added "free slots" to append other adapters with instructions.
* General insertion of instructions with newcomers in mind.

## Additional Notes
Currently tested on my machine and by @IsakNaslundBh .
There is an open issue which @IsakNaslundBh could not replicate. 
The export worked on my machine, then on closing and reopening Excel I could not make it work anymore. The issue seems to originate in the `Load Cases` sheet from the command:
`Create.Structure.LoadCombination?by_String_Int32_ListOfLoadcase_ListOfDouble_Boolean()`
which now fails constantly. Still trying to track why.

**Comment by alelom** [comment]
### WiX installer testing
See discussion in:
https://github.com/BuroHappoldEngineering/BHoM_Installer/pull/35

**Comment by awakeman** [comment]
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/13_Installers/BHoM%20BH%20Internal%20Use%20only/v2.3.alpha.6i/BHoM_v2.3.alpha.6i.msi?csf=1&e=5npnPI
