### ISSUE TITLE
Excel_Toolkit: Double push/run when there are IF statements

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#95]
When there are IF statements in an in cell formula, for example, putting in a conditional statement to control the 'TRUE' of the PUSH method so that it becomes true if another cell is triggered/modified.

**Comment by awakeman** [comment]
This affects more than just push but only really matters for methods which have side-effects, as push does. From what I can tell any time there is an IF in a cell it will be evaluated twice whenever one of the cells on which it depends changes (but *not* when you actively ask the cell to evaluate).

I am only able to see this by looking at where the call enters our code but it enters at the earliest point in our code so it does seem to be excel evaluating it twice. 

My immediate instinct is to debounce calls or otherwise have some boilerplate on our side that does nothing if the method is called from the same cell with the same inputs as the last time it ran. to avoid the double execution.
